### PR TITLE
Made it work for 1.9.3 as far as i can see, probably incompatible with < 1.9

### PR DESCRIPTION
**Pull request by lvonk**
Following is changed:
- jcode is not in ruby 1.9 anymore. So removed all dependencies there.
- jlength replaced with size.
- added '# encoding: UTF-8', apparently that is the new $KCODE. I did not find any other way of doing it for all files.
- added Dir.pwd to ruby load paths. For some reason it is not picking up the "!path's" from fitnesse. I don't know  when this is set? This should be fixed maybe you can help? See line 80 in statement_executor.rb

### CODE REVIEW

**Comment by lvonk** [comment]
Hi,

I noticed this pull request will break the use of characters like: é and such. Did this ever work in rubyslim?

I will investigate furthers.

**Comment by unclebob** [comment]
I've listed this on the download page of fitnese.org.  I don't want to pull it into the main line yet because most people are probably still using 1.9.

**Comment by lvonk** [comment]
Ok cool.

**Comment by dougbradbury** [comment]
Thanks for your contribution @lvonk. Master now supports 1.9.3 and there is a branch for legacy 1.8.7 support.

**Pull request closed without merging**
